on:
  push:
    branches: [master]
  pull_request:

jobs:
  test987:
    runs-on: ubuntu-latest
    if: false
    steps:
      - run: echo Hello world! && exit 0

  deploy:
    runs-on: ubuntu-latest
    needs: [test987]
    if:  always() && needs.test987.result != 'failed'
    steps:
      - run: echo "Deploying..."
